### ISSUE TITLE
新增文章时保存的时间不对

### ISSUE THREAD

**Issue by Brian-su888** [demozx/gf_cms#3]
新增文章时保持的时间不对，保存的时候少了8个小时，时区是否需要配置，程序会取系统的时区吧？
debug的时候看执行的插入sql语句时区是对的，新增文章后在数据库里看文章的创建时间少8个小时，希望看下什么问题

**Comment by demozx** [comment]
> 新增文章时保持的时间不对，保存的时候少了8个小时，时区是否需要配置，程序会取系统的时区吧？ debug的时候看执行的插入sql语句时区是对的，新增文章后在数据库里看文章的创建时间少8个小时，希望看下什么问题

好的，我看一下

**Comment by demozx** [comment]
> > 新增文章时保持的时间不对，保存的时候少了8个小时，时区是否需要配置，程序会取系统的时区吧？ debug的时候看执行的插入sql语句时区是对的，新增文章后在数据库里看文章的创建时间少8个小时，希望看下什么问题
> 
> 好的，我看一下

问题已处理，config.yaml.example新增了timezone配置
