### ISSUE TITLE
添加文章及修改文章时指定发布时间不生效

### ISSUE THREAD

**Issue by Brian-su888** [demozx/gf_cms#4]
如题，添加文章有输入指定时间，但是添加的时候不会生效。
在编辑文章时，输入指定时间，也不会修改成功

**Comment by demozx** [comment]
> 如题，添加文章有输入指定时间，但是添加的时候不会生效。 在编辑文章时，输入指定时间，也不会修改成功

文章和图集发布时间无法自行维护的问题已修复
